# Generated by Django 5.0.6 on 2024-10-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_add_author', 'Can add author'), ('can_edit_author', 'Can edit author'), ('can_delete_author', 'Can delete author')]},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_list_book', 'Can list book'), ('can_add_book', 'Can add book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book'), ('can_borrow_book', 'Can borrow book'), ('can_return_book', 'Can return book')]},
        ),
        migrations.AlterModelOptions(
            name='borrowinghistory',
            options={'permissions': [('can_view_history', 'Can view History'), ('can_edit_history', 'Can edit History')]},
        ),
    ]
