# Generated by Django 5.0.6 on 2024-10-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_add_author', 'Can add author'), ('can_list_author', 'Can list author'), ('can_edit_author', 'Can edit author'), ('can_delete_author', 'Can delete author')]},
        ),
    ]
